#!/bin/sh

GITHUB_URL=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

# Check if the curl command is available
CURL=$(command -v curl 2>/dev/null)
if [ -z "$CURL" ]; then
  echo "curl: command not found. Aborting!"
  exit 1
fi

$CURL -Sso ~/.vim/autoload/pathogen.vim $GITHUB_URL
